# Generated by Django 4.2.3 on 2023-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(db_column='professor_id', primary_key=True, serialize=False, verbose_name='id profesor')),
                ('name', models.CharField(db_column='name', max_length=40, verbose_name='nombre')),
                ('global_evaluation', models.FloatField(db_column='g_evaluation', null=True, verbose_name='campo evaluacion')),
                ('global_knowledge', models.FloatField(db_column='g_knowledge', null=True, verbose_name='campo conocimiento')),
                ('global_punctuality', models.FloatField(db_column='g_punctuality', null=True, verbose_name='campo puntualidad')),
                ('global_difficult', models.FloatField(db_column='g_difficult', null=True, verbose_name='campo dificultad')),
                ('global_dedication', models.FloatField(db_column='g_dedication', null=True, verbose_name='campo dedicacion')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'db_table': 'Professor',
            },
        ),
    ]
