# Generated by Django 4.2.3 on 2023-08-21 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id_profesor')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('knowledge', models.PositiveSmallIntegerField(choices=[(6, 'Muy malo'), (7, 'Malo'), (8, 'Regular'), (9, 'Bueno'), (10, 'Muy bueno')], default=8, validators=[django.core.validators.MinValueValidator(6, message='La puntuación debe ser igual o mayor a 6.'), django.core.validators.MaxValueValidator(10, message='La puntuación debe ser igual o menor a 10.')], verbose_name='conocimiento')),
                ('punctuality', models.PositiveSmallIntegerField(choices=[(6, 'Muy malo'), (7, 'Malo'), (8, 'Regular'), (9, 'Bueno'), (10, 'Muy bueno')], default=8, validators=[django.core.validators.MinValueValidator(6, message='La puntuación debe ser igual o mayor a 6.'), django.core.validators.MaxValueValidator(10, message='La puntuación debe ser igual o menor a 10.')], verbose_name='puntualidad')),
                ('difficult', models.PositiveSmallIntegerField(choices=[(6, 'Muy malo'), (7, 'Malo'), (8, 'Regular'), (9, 'Bueno'), (10, 'Muy bueno')], default=8, validators=[django.core.validators.MinValueValidator(6, message='La puntuación debe ser igual o mayor a 6.'), django.core.validators.MaxValueValidator(10, message='La puntuación debe ser igual o menor a 10.')], verbose_name='dificultad')),
                ('following', models.PositiveSmallIntegerField(choices=[(6, 'Muy malo'), (7, 'Malo'), (8, 'Regular'), (9, 'Bueno'), (10, 'Muy bueno')], default=8, validators=[django.core.validators.MinValueValidator(6, message='La puntuación debe ser igual o mayor a 6.'), django.core.validators.MaxValueValidator(10, message='La puntuación debe ser igual o menor a 10.')], verbose_name='seguimiento')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'db_table': 'Professor',
            },
        ),
    ]
