# Generated by Django 4.2.3 on 2023-08-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('cve', models.AutoField(primary_key=True, serialize=False, verbose_name='clave')),
                ('name', models.CharField(max_length=25, verbose_name='materia')),
                ('professors', models.ManyToManyField(to='professors.professor')),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_horario')),
                ('json_schedule', models.JSONField(verbose_name='horario_JSON')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='id_estudiante')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_comentario')),
                ('opinion', models.TextField(verbose_name='opinion')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='id_profesor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='id_estudiante')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'db_table': 'Comment',
            },
        ),
    ]
