# Generated by Django 4.2.3 on 2023-09-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('professors', '0001_initial'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='id estudiante'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='professor_id',
            field=models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='id profesor'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='id_usuario'),
        ),
    ]
